name: Lint
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - run: bundle exec danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
